version: "3.0"

services:
    mysql8:
        image: mysql:8.0.39
        restart: always
        command:
            -   --default_authentication_plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: root
        volumes:
            #      设置初始化脚本
            -  ./script/mysql/:/docker-entrypoint-initdb.d/
        ports:
            #      注意这里我映射为了 13316 端口
            -   "13306:3306"
    redis:
        image: redis:latest
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
        ports:
            - '16379:6379'

    etcd:
        image: 'bitnami/etcd:3.5'
        environment:
            - ALLOW_NONE_AUTHENTICATION=yes
        ports:
            #      所以你要用 12379 端口来连接 etcd
            - "12379:2379"
    mongo:
        image: mongo:8.0.0
        restart: always
        environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: root
        ports:
          - "27017:27017"