apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webook-mysql-claim
spec:
  storageClassName: webook-mysql
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

