apiVersion: v1
kind: PersistentVolume
metadata:
  name: webook-msyql-pv

spec:
  storageClassName: webook
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/webook"