apiVersion: v1
kind: Service
metadata:
  name: webook-mysql
spec:
  selector:
    app: webook-mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 30330
  type: NodePort

