global:
  external_labels:
    monitor: 'prometheus-monitor'

scrape_configs:
  - job_name: "webook"
    scrape_interval: 5s
    scrape_timeout: 3s
    static_configs:
      //访问webook上的数据采集地址
      - targets: [ "host.docker.internal:8081"]